### ISSUE TITLE
Statements for diverging values

### ISSUE THREAD

**Issue by Baranowski** [danr/contracts#2]
I've been playing with the idea of verifying that a value diverges or is successfully evaluated. I seem to be getting incorrect results when trying to verify that function terminates. Here is a little module I wrote:

``` Haskell
module NotStmt where

import Contracts

data Nat = Z | S Nat
data Fixed = Fixed

false_stmt_sat :: Statement Fixed
false_stmt_sat = Fixed ::: (Pred $ const False)

not_stmt :: Statement a -> Statement (Assuming a Fixed)
not_stmt s = s :=> false_stmt_sat

inf :: Nat -> Nat
inf x = inf (S x)

half :: Nat -> Nat
half (S (S x)) = S (half x)
half _ = Z

inf_divergent = inf ::: CF --> (CF :&: (Pred $ const False))
inf_ends_sat = not_stmt inf_divergent
half_divergent_sat =  half ::: CF --> (CF :&: (Pred $ const False))
half_ends = not_stmt half_divergent_sat
```

The function `inf` always diverges and `half` always terminates. Therefore `inf` complies with a false contract (`inf_divergent`) and `half` does not (`half_divergent_sat`).

Then I decided to verify that `half` terminates. To this end I defined a false statement (`false_stmt`) and used it to define a statement negation (`not_stmt`). And so `half_ends` states that `half_divergent_sat` is not true, i.e., that half is not equal to unr. It seems to me it should be true, but verification of this statement also fails.

I believe I understand translation to FOL quite well and I am aware of the unpredictable behaviour of statement implication caused by the unr constant. Yet, I think the statements above should work as expected. Am I missing something or is it some bug?

**Comment by danr** [comment]
Thank you, Wojciech.

The problem seems to be in the infamous "min-translation", which is not
part of the POPL-paper, and rightly so, because if it is turned off with
the flag --no-min, the file generated for half_ends is unsatisfiable rather
than satisfiable. This is to be expected, because you assume a false
contract (namely half_divergent_sat), and then everything is
true/unsatisfiable.

/Dan

**Comment by Baranowski** [comment]
Thank you, Dan.

That indeed fixes it. Could you perhaps suggest some place in the code where I might look to better understand min-translation?

**Comment by ntc2** [comment]
I don't know if this is the same min-translation used in the earlier
version I worked on in Winter 2011, but I describe the earlier
min-translation in a paper

http://web.cecs.pdx.edu/~ntc2/pub/rpe-paper.pdf

and some slides

http://web.cecs.pdx.edu/~ntc2/pub/rpe-slides.pdf

I prepared for my "research proficiency exam".

Cheers,

-nathan

**Comment by Baranowski** [comment]
Great, thank you!
